### ISSUE TITLE
ERROR: cf-shap is not a valid editable requirement.

### ISSUE THREAD

**Issue by Dima-Ramadan** [jpmorganchase/cf-shap#3]
Hi, 

I'm trying to install the package but I keep getting an error. I'm using the following command.

`pip install -e cf-shap`
`ERROR: cf-shap is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).`

any suggestions for the problem? 

thanks

**Comment by emanuele-albini** [comment]
Hi,

As stated by the error message, when using the `pip install -e DIRECTORY` command make sure that `DIRECTORY`  is the directory where this repository was cloned. Use `pip install --help` for more information.

Have a good one,
Emanuele
